name: deploy
on:
  push:
    branches:
      - main
      - dev

jobs:
    deploy:
      runs-on: ubuntu-latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
     
      
      - name: Init terraform
        run: terraform -chdir=terraform init 
      
      - name: Run terraform
        run: terraform -chdir=terraform apply -auto-approve -var="stage=$GITHUB_REF_NAME" -var="region=${{ secrets.AWS_REGION }}"  -var="client_id=${{ secrets.OKTA_CLIENT_ID }}" -var="issuer=${{ secrets.OKTA_ISSUER }}"

      - name: Run build client
        run: |
          cd client
          npm ci
          npm run build 
          npm test
          cd ..

      - name: Deploy pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with: 
          branch: gh-pages
          folder: client/build


